version: "3.9"

services:
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant/storage:/qdrant/storage
  # dash:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8050:8050"
  #   environment:
  #     - QDRANT_HOST=qdrant
  #     - QDRANT_PORT=6333
  #     - QDRANT_API_KEY=${QDRANT_API_KEY}
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - COHERE_API_KEY=${COHERE_API_KEY}
  #   volumes:
  #     - ./frontend:/app
